---
title: Suspicious Solution
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Blog created by a young Software Developer to all the people who want
  to learn and having fun like me.

'
permalink: ":title/"
baseurl: ''
url: ''
site-twitter: 
author: Guillermo Navarro
author-img: guillermo-navarro.jpg
about-author: I am a young software developer, always looking for adventures and good
  practices with code.
social-twitter: 
social-facebook: guillermo.navarromancillas
social-github: guille1194
social-linkedin: guillermo-navarro-mancillas-168232120
social-email: guillermo.navarro@tectijuana.edu.mx
discus-identifier: https-guille1194-github-io-suspicious-solution-2
analytics: UA-138139268-1
adsense: ca-pub-2224496275844265
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji
paginate: 8
paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
