title: Suspicious Solution
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/suspicious-solution" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Guillermo Navarro # add your name
author-img: guillermo-navarro.jpg # add your photo
about-author: I am a young software developer, always looking for adventures good code. # add description
social-twitter: # add your Twitter handle
social-facebook: guillermo.navarromancillas # add your Facebook handle
social-github: guille1194 # add your Github handle
social-linkedin: guillermo-navarro-mancillas-168232120 # add your Linkedin handle
social-email: guillermo.navarro@gmail.com # add your Email address

# Disqus
discus-identifier: https-guille1194-github-io-suspicious-solution-2 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
